#!/usr/bin/env sh
# Load Husky
. "$(dirname -- "$0")/_/husky.sh"

echo "Styling, testing, and building your project before committing..."

# Check TypeScript type standards
npm run check-types || {
    echo "Failed type check. Make the required changes listed above."
    exit 1
}

# Check Prettier format standards
npm run check-format || {
    echo "Prettier check failed. Run 'npm run format', add changes, and try committing again."
    exit 1
}

# Check ESLint code quality standards
npm run check-lint || {
    echo "ESLint check failed. Make the required changes listed above, add changes, and try committing again."
    exit 1
}

# Build the project
echo "The code looks fine. Building now..."
npm run build || {
    echo "The Next build failed. View the errors listed above to see why."
    exit 1
}

# Commit if everything passes
echo "The Next build succeeded. Committing now..."
